### ISSUE TITLE
GPUImage2

### ISSUE THREAD

**Issue by weixiyen** [YuAo/YUGPUImageHighPassSkinSmoothing#1]
Hi Yu,

Would it be possible to port YUGPUImageHighPassSkinSmoothing over for the next version of GPUImage -> GPUImage2?

https://github.com/BradLarson/GPUImage2/issues/14

**Comment by YuAo** [comment]
I don't have the time to do this currently.
However, since you've got the basic idea and all the codes/shaders, it is trivial to port this filter to GPUImage2.

**Comment by weixiyen** [comment]
Got it, will publish it once I get it working.  Thanks!

**Comment by YuAo** [comment]
Fell free to ask if you have any questions. : )
