### ISSUE TITLE
Skin Imperfection check

### ISSUE THREAD

**Issue by SaraMicheal** [YuAo/YUGPUImageHighPassSkinSmoothing#2]
Hello @YuAo ,

I have checked your library and its really good.Thank you. 

I want to detect skin imperfection like wrinkles, spots, acne, texture, and dark circles etc. 
Also i want to check percentage for this imperfection. I have checked "GPUImageSkinToneFilter" but i can not replicate related to imperfection. Can you please help me in this ?

Thanks.

**Comment by YuAo** [comment]
See https://github.com/YuAo/YUCIHighPassSkinSmoothing/issues/18
